language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
  # TODO: Uncomment when Travis jRuby will support C extensions for WSK
  # - jruby-18mode
  # - jruby-19mode
  # - jruby-head
